import { MoonIcon, SunIcon, LaptopIcon } from "@radix-ui/react-icons";
import {
  IconBrandGoogleFilled,
  IconBrandGithubFilled,
  IconHome,
  IconBook,
  IconSettings,
  IconPlus,
  IconSparkles,
  IconLogout,
  IconLayoutDashboard,
  Icon3dCubeSphere,
  IconRouteSquare,
  IconDatabase,
  IconChevronRight,
  IconChevronDown,
  IconKey,
  IconRobotFace,
  IconPointFilled,
  IconChartArea,
  IconPlug,
  IconCopy,
  IconCheck,
  IconSearch,
  IconExternalLink,
  IconChevronLeft,
  IconLock,
  IconListDetails,
} from "@tabler/icons-react";

const Icons = {
  MoonIcon,
  SunIcon,
  LaptopIcon,
  GoogleIcon: IconBrandGoogleFilled,
  GithubIcon: IconBrandGithubFilled,
  HomeIcon: IconHome,
  BookIcon: IconBook,
  SettingsIcon: IconSettings,
  PlusIcon: IconPlus,
  SparklesIcon: IconSparkles,
  LogoutIcon: IconLogout,
  DashboardIcon: IconLayoutDashboard,
  CubeIcon: Icon3dCubeSphere,
  RouteIcon: IconRouteSquare,
  DatabaseIcon: IconDatabase,
  ChevronRIghtIcon: IconChevronRight,
  ChevronDownIcon: IconChevronDown,
  KeyIcon: IconKey,
  RobotIcon: IconRobotFace,
  PointIcon: IconPointFilled,
  AreaIcon: IconChartArea,
  PlugIcon: IconPlug,
  CopyIcon: IconCopy,
  CheckIcon: IconCheck,
  SearchIcon: IconSearch,
  ExternalLinkIcon: IconExternalLink,
  ChevronLeftIcon: IconChevronLeft,
  LockIcon: IconLock,
  ListIcon: IconListDetails,
};

export default Icons;
